## Pandas 통계함수
- 데이터에 대한 통계 계산을 Pandas 통계함수를 사용하여 통계값 산출 가능
- Pandas는 배열의 주어진 요소로 부터 최소, 최대, 평균, 분산, 표준편차 등을 찾는데 유용한 통계함수가 존재
- 통계함수는 배열에서 요소별로 작동하며 axis옵션을 통해 연산 방향을 지정할 수 있음
    - axis=0 : 행과 행의 연산결과를 반환(기본값)
    - axis=1 : 열과 열의 연산결과를 반환
- describe, sum, min, max, mean, count, std, var, prod, corr, argmin, argmax, cumsum, cumprod 등

### `describe()` 요약통계
- 전반적인 기술통계 정보를 확인할 수 있음
- 기본값으로 수치형(Numeric) 컬럼에 대한 통계표를 보여줌
    - count:데이터개수, mean:평균, std:표준편차, <br>
    min:최소값, 25%:1분위수(하위25%값), 50%:2분위수(중앙값), 75%:3분위수(상위25%값), max:최대값

In [3]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [34]:
# 시간대별 교통사고.csv 파일 읽기
with open('/content/drive/MyDrive/시간대별 교통사고.csv','r',encoding='EUC-KR') as f:
    df = pd.read_csv(f)

df.head(5)

  요일      시간대  사고건수  사망자수  중상자수  경상자수  부상신고자수
0  일  00시-02시  1182    37   312  1417     113
1  일  02시-04시   783    23   252   832      79
2  일  04시-06시   589    21   194   621      70
3  일  06시-08시   729    24   257   688      67
4  일  08시-10시  1227    24   367  1321     125

In [35]:
df.describe()

              사고건수       사망자수         중상자수         경상자수      부상신고자수
count    84.000000  84.000000    84.000000    84.000000   84.000000
mean   2360.666667  30.369048   630.821429  2518.678571  229.059524
std    1255.331918   7.692556   303.854402  1367.701741  125.066378
min     374.000000  14.000000   131.000000   358.000000   34.000000
25%    1177.750000  25.750000   314.250000  1229.250000  113.000000
50%    2559.500000  30.000000   676.500000  2756.000000  247.000000
75%    3376.250000  35.000000   894.750000  3683.750000  331.000000
max    4873.000000  51.000000  1214.000000  5130.000000  459.000000

#### `count()` 데이터의 개수
- NaN을 제외한 데이터의 개수 계산

```
# 전체 데이터
dataframe.count()
# 단일 컬럼의 데이터
dataframe['<컬럼명>'].count()
```

In [7]:
# DataFrame 전체 데이터의 개수
df.count()

요일        84
시간대       84
사고건수      84
사망자수      84
중상자수      84
경상자수      84
부상신고자수    84
dtype: int64

In [36]:
# '사고건수' 컬럼의 데이터 개수
df['사고건수'].count()

84

### `mean()` 평균
- NaN을 제외한 데이터의 평균 계산
- 조건별 평균도 계산 가능

```
# 전체 데이터의 평균
dataframe.mean()
# 컬럼의 평균
dataframe['<컬럼명>'].mean()
# 조건별 평균(조건식에 맞는 컬럼 데이터의 평균)
dataframe.loc[<조건식>, '<컬럼명>'].mean()
```

In [10]:
# NaN을 제외한 데이터의 평균 계산
# df.mean()

In [32]:
# 컬럼의 평균
df.loc[:,'사고건수':].mean()

Series([], dtype: float64)

In [13]:
# 조건별 평균
condition = (df['요일'] == '월')
df.loc[condition, '사고건수'].mean()

2394.5833333333335

### `skipna=True` 옵션
- NaN의 값을 제외하고 기술통계함수를 실행
- `skipna=False`로 설정하면 NaN값이 있는 컬럼은 NaN으로 출력

In [19]:
df_missing = pd.read_csv('/content/drive/MyDrive/missing_data_test .csv', encoding = 'EUC-KR')

In [21]:
try:
    with open('/content/drive/MyDrive/missing_data_test .csv','r',encoding='EUC-KR') as f:
        df_missing = pd.read_csv(f)
        print('파일읽기 성공')
except:
  print('파일읽기 실패')

파일읽기 성공

In [22]:
df_missing

     연도    제품1  제품2    제품3    제품4
0  2015  250.0  150    NaN    NaN
1  2016  200.0  160  170.0    NaN
2  2017  150.0  200  100.0  150.0
3  2018  120.0  230  130.0  170.0
4  2019    NaN  250  140.0    NaN

In [23]:
# skipna=True의 평균
df_missing.mean(skipna=True)

연도     2017.0
제품1     180.0
제품2     198.0
제품3     135.0
제품4     160.0
dtype: float64

In [24]:
# skipna=False의 평균
df_missing.mean(skipna=False)

연도     2017.0
제품1       NaN
제품2     198.0
제품3       NaN
제품4       NaN
dtype: float64

### `median()` 중앙값
- 데이터의 중앙값을 출력
- 이상치(outlier)가 존재하는 경우, 평균보다 중앙값을 대표값으로 선호

In [25]:
pd.Series([1,2,3,4,5]).median # 중앙값

3.0

In [28]:
pd.Series([5,4,1,2,99]).mean()

22.2

In [29]:
pd.Series([5,4,1,2,99]).median()

4.0

In [30]:
pd.Series([1,2,3,4,5,6]).median()

3.5

In [39]:
print(f"""\
        평균: {df['사고건수'].mean()},
        중앙값: {df['사고건수'].median()},
        차이 : {df['사고건수'].mean() - df['사고건수'].median()}""")

        평균: 2360.6666666666665,
        중앙값: 2559.5,
        차이 : -198.83333333333348

### `sum()` 합계
- NaN을 제외한 데이터의 합계
    - 문자열 컬럼은 모든 데이터가 붙어서 출력될 수 있음

In [41]:
df.tail(5)

   요일      시간대  사고건수  사망자수  중상자수  경상자수  부상신고자수
79  토  14시-16시  3444    34   910  4222     389
80  토  16시-18시  3472    31   940  4269     400
81  토  18시-20시  3298    28   940  3704     334
82  토  20시-22시  2569    21   688  2876     236
83  토  22시-24시  1699    30   449  1910     150

In [42]:
df['요일'] = '월'

In [44]:
df.sum()

요일        월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월월...
시간대       00시-02시02시-04시04시-06시06시-08시08시-10시10시-12시12시-...
사고건수                                                 198296
사망자수                                                   2551
중상자수                                                  52989
경상자수                                                 211569
부상신고자수                                                19241
dtype: object

In [45]:
df['사망자수'].sum()

2551

### `cumsum()` 누적합과 `cumprod()` 누적곱
- 누적되는 합계
```
dataframe.cumsum()
dataframe['<컬럼명>'].cumsum()
```

- 누적곱을 구할 수 있으나, 일반적으로 값이 너무 커지므로 잘 활용하지 않음
```
dataframe.cumprod()
dataframe['<컬럼명>'].cumprod()
```

In [46]:
# 사고건수의 누적합
df['사고건수'].cumsum()

0       1182
1       1965
2       2554
3       3283
4       4510
       ...
79    187258
80    190730
81    194028
82    196597
83    198296
Name: 사고건수, Length: 84, dtype: int64

In [47]:
df['사고건수누적'] = df['사고건수'].cumsum()
df.head(5)

  요일      시간대  사고건수  사망자수  중상자수  경상자수  부상신고자수  사고건수누적
0  월  00시-02시  1182    37   312  1417     113    1182
1  월  02시-04시   783    23   252   832      79    1965
2  월  04시-06시   589    21   194   621      70    2554
3  월  06시-08시   729    24   257   688      67    3283
4  월  08시-10시  1227    24   367  1321     125    4510

In [48]:
# 사고건수의 누적곱
df['사고건수'].cumprod()

0                1182
1              925506
2           545123034
3        397394691786
4     487603286821422
           ...
79                  0
80                  0
81                  0
82                  0
83                  0
Name: 사고건수, Length: 84, dtype: int64

### `var()` 분산과 `std()` 표준편차
- 분산 : 어떤 대상의 흩어진 정보나 상태로 편차의 제곱의 평균값
- 표준편차 : 자료의 산포도를 나타내는 수치로, 분산의 제곱근

In [49]:
# 사고건수의 분산
df['사고건수'].var()

1575858.2248995975

In [50]:
# 사고건수의 표준편차
df['사고건수'].std()

1255.331918219081

### `min()` 최소값과 `max()` 최대값

In [51]:
# 사망자수의 최소값
df['사망자수'].min()

14

In [52]:
# 사망자수의 최대값
df['사망자수'].max()

51

### `unique()` 고유값과 `nunique()` 고유값 개수
- 고유값과 고유값의 개수를 구하고자 할 때 사용
- 일반적으로 문자열 컬럼에 사용

In [57]:
df['시간대'].head(3)

0    00시-02시
1    02시-04시
2    04시-06시
Name: 시간대, dtype: object

In [53]:
# 시간대의 고유값
df['시간대'].unique()

array(['00시-02시', '02시-04시', '04시-06시', '06시-08시', '08시-10시', '10시-12시',
       '12시-14시', '14시-16시', '16시-18시', '18시-20시', '20시-22시', '22시-24시'],
      dtype=object)

In [58]:
# 시간대의 고유값 개수
df['시간대'].nunique()

12

### `quantile(r)` 분위수
- 분위수는 주어진 데이터를 동등한 크기로 분할하는 지점
- r은 0부터 1의 값을 가지며, 하위 r%의 값을 계산
    - 10%의 경우 0.1, 80%의 경우 0.8

In [ ]:
# 전체 데이터의 분위수
# df.quantile(0.25), df.quantile(0.5), df.quantile(0.75)

In [59]:
# 사고건수의 하위10%의 값
df['사고건수'].quantile(0.1)

654.4

In [60]:
df['사고건수'].quantile(0.5), df['사고건수'].median()

(2559.5, 2559.5)

In [61]:
df['사고건수'].quantile(1), df['사고건수'].max()

(4873.0, 4873)

In [62]:
df['사고건수'].min(), df['사고건수'].quantile(0)

(374, 374.0)

In [63]:
# 사고건수의 상위 20%값 (하위 80%)
df['사고건수'].quantile(0.8)

3523.4

### `mode()` 최빈값
- 가장 많이 출현한 데이터
- 카테고리형 데이터에도 적용 가능

In [64]:
d = pd.DataFrame({'A':[1,1,1,1,1,2,2,2,2]})
d

   A
0  1
1  1
2  1
3  1
4  1
5  2
6  2
7  2
8  2

In [65]:
d['A'].mode()

0    1
Name: A, dtype: int64

In [66]:
# 사고건수의 최빈값
df['사고건수'].mode() # 겹치는 값이 없어 여러개 출력

0      374
1      403
2      431
3      467
4      488
      ...
79    4165
80    4233
81    4271
82    4708
83    4873
Name: 사고건수, Length: 84, dtype: int64

In [72]:
# 시간대의 최빈값
df['시간대'].mode()

0     00시-02시
1     02시-04시
2     04시-06시
3     06시-08시
4     08시-10시
5     10시-12시
6     12시-14시
7     14시-16시
8     16시-18시
9     18시-20시
10    20시-22시
11    22시-24시
Name: 시간대, dtype: object

### `corr()` 상관계수
- 데이터프레임의 컬럼별 상관관계를 확인할 수 있음

In [74]:
df_corr = pd.read_csv('/content/drive/MyDrive/swiss.csv',
                      encoding = 'EUC-KR', index_col = 0)
# index_col = 0 첫번째 열에 있는 값을 인덱스로 인식해서 가져와라!
# 모르겠으면 index_col = 0 삭제하고 실행해보기
df_corr.head(5)

              Fertility  Agri  Exam  Edu   Cath  Infan
Courtelary         80.2  17.0    15   12   9.96   22.2
Delemont           83.1  45.1     6    9  84.84   22.2
Franches-Mnt       92.5  39.7     5    5  93.40   20.2
Moutier            85.8  36.5    12    7  33.77   20.3
Neuveville         76.9  43.5    17   15   5.16   20.6

In [ ]:
# 전체 데이터 상관계수
df_corr.corr()

In [76]:
# Edu의 상관관계
df_corr.corr()['Edu']

Fertility   -0.663789
Agri        -0.639523
Exam         0.698415
Edu          1.000000
Cath        -0.153859
Infan       -0.099322
Name: Edu, dtype: float64

In [77]:
# Edu 와 Exam의 상관관계
df_corr['Edu'].corr(df_corr['Exam'])

0.6984152962884828

#### [연습문제]
[구별교통사고현황](https://drive.google.com/file/d/1bifVRWhPuXNrfXrGwL1gdqMZdvT6vwy5/view?usp=sharing)

In [101]:
try:
    # encoding = 'utf-8'이면 지정하지 않아도 됨
    with open('/content/drive/MyDrive/교통사고현황(구별).csv', 'r') as f:
      # index_col=0 옵션은 pd.read_csv()에 적용해야 함
      # open()은 단순히 파일을 읽는 역할만 하므로 index_col을 사용할 수 없음
      car = pd.read_csv(f, index_col=0)
      print("파일읽기 성공")
except:
    print("파일읽기 실패")

파일읽기 성공

In [103]:
car.head()

      2014  2015  2016  2017  2018  2019  2020  2021  2022  2023
자치구별
종로구   1314  1414  1299  1190  1134  1133   903   778   974   988
중구    1305  1338  1288  1252  1128  1184   955   854   943   931
용산구   1350  1516  1428  1337  1330  1187   890  1014  1014   996
성동구   1189  1227  1099  1076  1143  1091  1119  1057   948   919
광진구   1480  1235  1045  1064  1108   973   869   922   708   717

In [104]:
# 결측치가 있나요?
# 결측치가 없다 not null
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 종로구 to 강동구
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2014    25 non-null     int64
 1   2015    25 non-null     int64
 2   2016    25 non-null     int64
 3   2017    25 non-null     int64
 4   2018    25 non-null     int64
 5   2019    25 non-null     int64
 6   2020    25 non-null     int64
 7   2021    25 non-null     int64
 8   2022    25 non-null     int64
 9   2023    25 non-null     int64
dtypes: int64(10)
memory usage: 2.1+ KB

In [105]:
# 서울시는 어느 연도에 교통사고가 가장 많이 일어났을까요?
car.sum(axis=0).sort_values(ascending=False).head(1)

2015    41665
dtype: int64

In [119]:
# 2020년, 어느 구에 교통사고가 가장 많이 일어났을까요?
car.sort_values(by='2020', ascending=False).head(1)
car['2020'].sort_values(ascending=False).head(1)

자치구별
강남구    3752
Name: 2020, dtype: int64

In [124]:
# 연도별 평균값을 기준으로 교통사고 top3구는?
car['평균값'] = car.mean(axis=1)
car['평균값'].sort_values(ascending=False).head(3)

자치구별
강남구    3727.9
송파구    2680.0
서초구    2274.7
Name: 평균값, dtype: float64

In [127]:
# '최근증가율' 컬럼을 추가하여 2023년 교통사고수와 2022년 사고수의 증가율을 계산
car['최근증가율'] = (car['2023'] - car['2022'])/car['2022']
car

,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,평균값,최근증가율
자치구별,,,,,,,,,,,,
종로구,1314,1414,1299,1190,1134,1133,903,778,974,988,1112.7,0.014374
중구,1305,1338,1288,1252,1128,1184,955,854,943,931,1117.8,-0.012725
용산구,1350,1516,1428,1337,1330,1187,890,1014,1014,996,1206.2,-0.017751
성동구,1189,1227,1099,1076,1143,1091,1119,1057,948,919,1086.8,-0.030591
광진구,1480,1235,1045,1064,1108,973,869,922,708,717,1012.1,0.012712
동대문구,1848,2085,2051,1718,1699,1565,1448,1390,1534,1674,1701.2,0.091265
중랑구,1622,1722,1535,1639,1565,1620,1447,1373,1401,1268,1519.2,-0.094932
성북구,1664,1680,1618,1557,1427,1509,1275,1285,1288,1256,1455.9,-0.024845
강북구,1313,1265,1227,1202,1216,1277,1087,1017,1044,972,1162.0,-0.068966
도봉구,919,914,949,944,824,852,741,591,522,530,778.6,0.015326
노원구,1516,1459,1535,1499,1569,1703,1462,1413,1384,1366,1490.6,-0.013006
은평구,1325,1203,1121,1067,1134,1119,953,867,918,1039,1074.6,0.131808
서대문구,1122,1071,1135,1032,1033,1113,928,930,974,916,1025.4,-0.059548
마포구,1759,1802,1768,1859,1671,1494,1272,1102,1065,1250,1504.2,0.173709
양천구,1466,1596,1493,1343,1428,1506,1344,1305,1165,1221,1386.7,0.048069
강서구,1806,1932,1691,1584,1502,1829,1575,1501,1606,1518,1654.4,-0.054795
구로구,1566,1508,1511,1433,1532,1529,1325,1350,1274,1359,1438.7,0.066719
금천구,1029,914,799,824,932,920,810,827,844,876,877.5,0.037915
영등포구,2193,2462,2403,2386,2493,2439,2208,2178,1998,1900,2266.0,-0.049049
동작구,1399,1386,1471,1409,1412,1406,1307,1148,1217,1242,1339.7,0.020542
관악구,1716,1625,1408,1251,1300,1363,1444,1419,1172,980,1367.8,-0.163823
서초구,2217,2160,2313,2361,2478,2418,2250,2118,2264,2168,2274.7,-0.042403
강남구,3624,3970,3828,3469,3459,3722,3752,3820,3709,3926,3727.9,0.058506
송파구,2608,2687,2598,2758,2860,2892,2595,2607,2581,2614,2680.0,0.012786
강동구,1442,1494,1426,1371,1418,1414,1268,1047,1151,1185,1321.6,0.029540

In [128]:
# 어느구의 최근증가율이 가장 높나요?
car['최근증가율'].sort_values(ascending=False).head(1)

자치구별
마포구    0.173709
Name: 최근증가율, dtype: float64

In [129]:
car_mean = pd.Series(car.mean(axis=1))
car_mean

자치구별
종로구     1019.976198
중구      1024.648940
용산구     1105.681854
성동구      996.230784
광진구      927.759393
동대문구    1559.440939
중랑구     1392.592089
성북구     1334.572930
강북구     1065.160920
도봉구      713.717944
노원구     1366.382250
은평구      985.060984
서대문구     939.945038
마포구     1378.864476
양천구     1271.145672
강서구     1516.528767
구로구     1318.813893
금천구      804.378160
영등포구    2077.162579
동작구     1228.060045
관악구     1253.803015
서초구     2085.138133
강남구     3417.246542
송파구     2456.667732
강동구     1211.469128
dtype: float64

In [137]:
# 2024년의 교통사고수 예측은? (이동평균법을 사용)
# 평균값으로 이미 구해짐
# 그렇다면 최근 5개년 것만 기준으로 한다고 했을 때
car['2024(e)'] = car.loc[:,'2019':'2023'].mean(axis=1)
car['2024(e)']

자치구별
종로구      955.2
중구       973.4
용산구     1020.2
성동구     1026.8
광진구      837.8
동대문구    1522.2
중랑구     1421.8
성북구     1322.6
강북구     1079.4
도봉구      647.2
노원구     1465.6
은평구      979.2
서대문구     972.2
마포구     1236.6
양천구     1308.2
강서구     1605.8
구로구     1367.4
금천구      855.4
영등포구    2144.6
동작구     1264.0
관악구     1275.6
서초구     2243.6
강남구     3785.8
송파구     2657.8
강동구     1213.0
Name: 2024(e), dtype: float64