# 1. GRDP와 사회조사지표, 인구통계자료 분석
- 지역내 총생산(Gross Regional Domestic Product : GRDP)
    - 연도별 지역내 총생산이 낮은지역, 높은 지역을 알아보자.
    - 2020년 대비 2023년 증감율을 기준으로 어느지역이 증가하고 감소했는지 알아보자.
- 2023년 GRDP와 사회조사지표, 인구통계자료를 통합하여 분석하여 보자.
    - 삶의 만족도와 다른 사회조사 지표, GRDP, 인구밀도와의 상관관계
    - 인구통계와 사회조사지표간의 상관관계
- Datasets
    - [인당GRDP](https://drive.google.com/file/d/1rStpubT6xNyjwhu9y6BSHGmQml6VvLV3/view?usp=sharing)
    - [사회조사지표](https://drive.google.com/file/d/1qN9rxS61N66mCHl16wBPnQceioLdieuG/view?usp=sharing)
    - [인구통계](https://drive.google.com/file/d/1LSRIDYanuDVQLPBMp5oL2kxeIrKP7GYu/view?usp=sharing)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# csv 파일읽기
# 주어진 파일의 encoding을 자동으로 검사한 후 pandas를 통해 파일을 읽음.
import chardet

def read_csv_file(file_path, index_col=0):
    try:
        # 1. 파일을 바이너리 모드('rb')로 읽고, 인코딩 감지
        with open(file_path, 'rb') as f :
            result = chardet.detect(f.read())

        # 2. 감지된 인코딩을 사용하여 CSV 파일 읽기
        df = pd.read_csv(file_path,
                         encoding=result['encoding'],
                         index_col=index_col)

    except Exception as e:
        print(f"Error:{e}")

    return df # 성공적으로 읽은 DataFrame 반환

In [ ]:
# 인당 GRDP 파일읽기
grdp = pd.read_csv('/content/drive/MyDrive/1인당_GRDP_시도_15_23.csv',encoding='EUC-KR'
                    ,index_col=0)
grdp

          2015   2016   2017   2018   2019   2020   2021   2022  2023 p)
행정구역별
서울특별시    38911  41359  43731  46547  48248  49165  53373  56094    58255
부산광역시    25707  26800  27210  28355  29436  29272  31950  34465    34762
대구광역시    22685  23382  24170  24820  25653  25928  27770  29654    30985
인천광역시    28376  29864  31198  31688  32272  32292  35388  38065    38840
광주광역시    24731  26248  27449  28594  29807  30823  32098  33497    35452
대전광역시    24568  26265  27281  28027  29870  31276  32928  34409    36645
울산광역시    65408  65031  66786  65897  65486  59529  70889  76234    81235
세종특별자치시  53194  46767  44964  41137  40597  40212  42797  42207    43174
경기도      32590  34399  37146  38541  38135  38890  41392  42903    43070
강원특별자치도  27608  29380  31200  32267  33780  33945  36350  37797    40713
충청북도     36656  39848  43254  46002  46777  46462  49519  52252    54214
충청남도     49568  51891  55839  56126  54857  56448  62474  64469    64709
전북특별자치도  26827  27300  28545  29319  30400  31213  33164  34484    36283
전라남도     40834  42473  43582  44086  44535  45339  52489  54179    55513
경상북도     40916  41820  43005  43129  42598  42263  44957  46243    48812
경상남도     32739  34005  33985  34291  35355  34325  35661  38612    42144
제주특별자치도  30275  32389  34134  33673  33545  32404  33861  35999    38450

In [ ]:
# 2023 p) 컬럼 이름 변경
grdp.rename(columns={'2023 p)':'2023'}, inplace=True)
grdp.head()

        2015   2016   2017   2018   2019   2020   2021   2022   2023
행정구역별
서울특별시  38911  41359  43731  46547  48248  49165  53373  56094  58255
부산광역시  25707  26800  27210  28355  29436  29272  31950  34465  34762
대구광역시  22685  23382  24170  24820  25653  25928  27770  29654  30985
인천광역시  28376  29864  31198  31688  32272  32292  35388  38065  38840
광주광역시  24731  26248  27449  28594  29807  30823  32098  33497  35452

In [ ]:
# 연도별 GRDP가 높은 지역
grdp.sum(axis=1).sort_values(ascending=False).head(1)

행정구역별
울산광역시    616495
dtype: int64

In [ ]:
### 풀이
# 연도별 GRDP가 높은 지역
                    # 1) 열방향으로 최대값의 인덱스 찾기
highest = grdp.index[np.argmax(grdp, axis=0)]
      # 2) 반환된 인덱스 번호를 이용해 원래 DataFrame의 인덱스 레이블 찾기

lowest = grdp.index[np.argmin(grdp, axis=0)]
highest, lowest
#grdp.idxmax(axis=0), grdp['2023'].idxmin(axis=0)

(Index(['울산광역시', '울산광역시', '울산광역시', '울산광역시', '울산광역시', '울산광역시', '울산광역시', '울산광역시',
        '울산광역시'],
       dtype='object', name='행정구역별'),
 Index(['대구광역시', '대구광역시', '대구광역시', '대구광역시', '대구광역시', '대구광역시', '대구광역시', '대구광역시',
        '대구광역시'],
       dtype='object', name='행정구역별'))

In [ ]:
# 2020년 대비 2023년 증감율
grdp['증감율'] = (grdp['2023'] - grdp['2020'])/grdp['2020']
grdp['증감율'].sort_values(ascending=False)

행정구역별
울산광역시      0.364629
경상남도       0.227793
전라남도       0.224398
인천광역시      0.202775
강원특별자치도    0.199381
대구광역시      0.195040
부산광역시      0.187551
제주특별자치도    0.186582
서울특별시      0.184888
대전광역시      0.171665
충청북도       0.166846
전북특별자치도    0.162432
경상북도       0.154958
광주광역시      0.150180
충청남도       0.146347
경기도        0.107483
세종특별자치시    0.073660
Name: 증감율, dtype: float64

In [ ]:
# 사회조사 지표 파일 읽기
social = pd.read_csv('/content/drive/MyDrive/사회조사지표_시도_2023.csv', index_col=0)
social.head()

# 풀이
# social_path = '/content/drive/MyDrive/LikeLion/!수업자료/사회조사지표_시도_2023.csv'
# social = read_csv_file(social_path)
# social.head(2)

,삶의만족도,소득만족도,소득있음(%),소비생활만족도,범죄발생건수,응급의료시설수,월평균근무시간,실업률(%),문화예술스포츠관람건수
행정구역별,,,,,,,,,
서울특별시,3.352647,2.767233,80.1,2.922923,"277,213",65,41.72,2.638498,26.3
부산광역시,3.324000,2.782000,75.5,2.891000,106433,36,40.00,3.193613,22.1
대구광역시,3.283716,2.705000,74.7,2.825000,66674,21,40.44,2.953750,22.7
인천광역시,3.350350,2.718000,76.8,2.834166,87831,25,39.69,2.811127,28.5
광주광역시,3.392392,2.807000,76.2,2.896000,42058,26,37.55,2.581864,20.8

In [ ]:
# 인구통계 파일읽기
population_path = '/content/drive/MyDrive/인구통계_시도_2023.csv'
population = read_csv_file(population_path)
population.head(2)

            총인구 (명)  외국인(명)  고령자(70세이상)  노령화지수     인구밀도
행정구역별(읍면동)
서울특별시       9384512  366139     1068752  204.0  15506.4
부산광역시       3279604   63056      449806  227.7   4252.0

In [ ]:
# 인구통계의 컬럼명 변경
population = population.rename_axis('행정구역별')
# 인구통계의 인덱스명 변경
population = population.rename(index={'전라북도':'전북특별자치도'})
population

          총인구 (명)  외국인(명)  고령자(70세이상)  노령화지수     인구밀도
행정구역별
서울특별시     9384512  366139     1068752  204.0  15506.4
부산광역시     3279604   63056      449806  227.7   4252.0
대구광역시     2379188   43191      288128  181.8   1586.7
인천광역시     3025950  122050      285535  144.8   2835.7
광주광역시     1457090   35274      147071  136.7   2908.5
대전광역시     1470336   29434      146109  150.3   2724.0
울산광역시     1107432   31670       96479  128.4   1042.0
세종특별자치시    386261    7807       24024   57.9    830.7
경기도      13815367  652579     1244656  128.3   1354.5
강원특별자치도   1528014   33140      223419  234.7     90.8
충청북도      1641481   71311      199775  185.4    221.6
충청남도      2216332  126837      286242  179.5    268.7
전북특별자치도   1768491   52799      271041  228.0    219.1
전라남도      1776668   62493      303672  242.8    143.7
경상북도      2589880   91311      394090  236.8    140.6
경상남도      3271148  117235      400172  175.7    310.3
제주특별자치도    676767   28824       74217  134.9    365.8

In [ ]:
# 데이터 병합 (좌우)
df = pd.concat([grdp[['2023','증감율']], social, population], axis=1)
df.head(2)

,2023,증감율,삶의만족도,소득만족도,소득있음(%),소비생활만족도,범죄발생건수,응급의료시설수,월평균근무시간,실업률(%),문화예술스포츠관람건수,총인구 (명),외국인(명),고령자(70세이상),노령화지수,인구밀도
행정구역별,,,,,,,,,,,,,,,,
서울특별시,58255,0.184888,3.352647,2.767233,80.1,2.922923,"277,213",65,41.72,2.638498,26.3,9384512,366139,1068752,204.0,15506.4
부산광역시,34762,0.187551,3.324000,2.782000,75.5,2.891000,106433,36,40.00,3.193613,22.1,3279604,63056,449806,227.7,4252.0

In [ ]:
# 2023년 GRDP의 컬럼명 변경
df.rename(columns={'2023':'인당GRDP'}, inplace = True)
# df의 결측치 및 데이터 타입 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 서울특별시 to 제주특별자치도
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   인당GRDP       17 non-null     int64
 1   증감율          17 non-null     float64
 2   삶의만족도        17 non-null     float64
 3   소득만족도        17 non-null     float64
 4   소득있음(%)      17 non-null     float64
 5   소비생활만족도      17 non-null     float64
 6   범죄발생건수       17 non-null     object
 7   응급의료시설수      17 non-null     int64
 8   월평균근무시간      17 non-null     float64
 9   실업률(%)       17 non-null     float64
 10  문화예술스포츠관람건수  17 non-null     float64
 11  총인구 (명)      17 non-null     int64
 12  외국인(명)       17 non-null     int64
 13  고령자(70세이상)   17 non-null     int64
 14  노령화지수        17 non-null     float64
 15  인구밀도         17 non-null     float64
dtypes: float64(10), int64(5), object(1)
memory usage: 2.8+ KB

In [ ]:
# 범죄발생건수 숫자형으로 변환
df.loc['서울특별시','범죄발생건수'] = 277213

In [ ]:
# 범죄발생건수 숫자형 변환
df.loc['범죄발생건수'] = pd.to_numeric(df['범죄발생건수'])
df['범죄발생건수'].head()

행정구역별
서울특별시    277213
부산광역시    106433
대구광역시     66674
인천광역시     87831
광주광역시     42058
Name: 범죄발생건수, dtype: object

In [ ]:
# 변수간 상관분석
df_corr_matrix = df.corr()
df_corr_matrix

,인당GRDP,증감율,삶의만족도,소득만족도,소득있음(%),소비생활만족도,범죄발생건수,응급의료시설수,월평균근무시간,실업률(%),문화예술스포츠관람건수,총인구 (명),외국인(명),고령자(70세이상),노령화지수,인구밀도,"(서울특별시, 범죄발생건수)"
인당GRDP,1.000000,0.507548,-0.059102,0.041420,-0.072928,0.026768,0.023712,0.023238,0.208596,0.012776,-0.040835,0.030051,0.092204,0.044994,-0.019284,0.093322,NaN
증감율,0.507548,1.000000,-0.400500,-0.070686,-0.420848,-0.266553,-0.222852,-0.139467,0.015511,0.255416,-0.054610,-0.235725,-0.270468,-0.209302,0.196258,0.000937,NaN
삶의만족도,-0.059102,-0.400500,1.000000,0.730706,-0.010410,0.677007,-0.376393,-0.404501,-0.516408,-0.606907,-0.235972,-0.368048,-0.292256,-0.409869,-0.326487,-0.226046,NaN
소득만족도,0.041420,-0.070686,0.730706,1.000000,0.004785,0.838497,-0.458094,-0.393793,-0.830059,-0.501488,-0.494268,-0.461917,-0.407292,-0.430857,0.176753,-0.279217,NaN
소득있음(%),-0.072928,-0.420848,-0.010410,0.004785,1.000000,0.313403,0.423069,0.515928,-0.037156,-0.506426,0.126961,0.434716,0.455266,0.491770,0.265891,0.157845,NaN
소비생활만족도,0.026768,-0.266553,0.677007,0.838497,0.313403,1.000000,-0.115985,-0.088040,-0.607737,-0.447511,-0.275809,-0.124635,-0.111136,-0.072438,0.194277,0.087708,NaN
범죄발생건수,0.023712,-0.222852,-0.376393,-0.458094,0.423069,-0.115985,1.000000,0.909894,0.565259,0.199115,0.684571,0.997909,0.974563,0.982000,0.011641,0.528051,NaN
응급의료시설수,0.023238,-0.139467,-0.404501,-0.393793,0.515928,-0.088040,0.909894,1.000000,0.430235,0.060823,0.460842,0.914897,0.889578,0.937187,0.238590,0.361246,NaN
월평균근무시간,0.208596,0.015511,-0.516408,-0.830059,-0.037156,-0.607737,0.565259,0.430235,1.000000,0.458660,0.480474,0.557038,0.519607,0.521710,-0.339342,0.462748,NaN
실업률(%),0.012776,0.255416,-0.606907,-0.501488,-0.506426,-0.447511,0.199115,0.060823,0.458660,1.000000,0.297638,0.176669,0.085584,0.192608,0.097031,0.379708,NaN
문화예술스포츠관람건수,-0.040835,-0.054610,-0.235972,-0.494268,0.126961,-0.275809,0.684571,0.460842,0.480474,0.297638,1.000000,0.684904,0.681841,0.591271,-0.375964,0.384416,NaN
총인구 (명),0.030051,-0.235725,-0.368048,-0.461917,0.434716,-0.124635,0.997909,0.914897,0.557038,0.176669,0.684904,1.000000,0.983929,0.978047,-0.001774,0.484334,NaN
외국인(명),0.092204,-0.270468,-0.292256,-0.407292,0.455266,-0.111136,0.974563,0.889578,0.519607,0.085584,0.681841,0.983929,1.000000,0.942061,-0.074918,0.382490,NaN
고령자(70세이상),0.044994,-0.209302,-0.409869,-0.430857,0.491770,-0.072438,0.982000,0.937187,0.521710,0.192608,0.591271,0.978047,0.942061,1.000000,0.171740,0.555526,NaN
노령화지수,-0.019284,0.196258,-0.326487,0.176753,0.265891,0.194277,0.011641,0.238590,-0.339342,0.097031,-0.375964,-0.001774,-0.074918,0.171740,1.000000,0.076793,NaN
인구밀도,0.093322,0.000937,-0.226046,-0.279217,0.157845,0.087708,0.528051,0.361246,0.462748,0.379708,0.384416,0.484334,0.382490,0.555526,0.076793,1.000000,NaN
"(서울특별시, 범죄발생건수)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 삶의 만족도와 강한 상관관계 확인
df.corr()['삶의만족도'].sort_values(ascending=False).head()

## 풀이
high_relevance = abs(df_corr_matrix['삶의만족도'])>=0.7
df_corr_matrix[high_relevance].index

삶의만족도      1.000000
소득만족도      0.730706
소비생활만족도    0.677007
소득있음(%)   -0.010410
인당GRDP    -0.059102
Name: 삶의만족도, dtype: float64

In [ ]:
# 인구밀도와 강한 상관관계 확인
high_relevance = abs(df_corr_matrix['총인구 (명)'])>=0.7
df_corr_matrix[high_relevance].index

Index(['범죄발생건수', '응급의료시설수', '총인구 (명)', '외국인(명)', '고령자(70세이상)'], dtype='object')

In [ ]:
# 변수에 대한 상관관계가 높은 변수명 출력 함수
def high_relevance(df, label, threshold=0.7):
    df_corr_matrix = df.corr()
    high_relevance = abs(df_corr_matrix[label])>=threshold
    relevance_list = list(df_corr_matrix[high_relevance].index)
    relevance_list.remove(label) #변수(자기자신) 삭제
    return relevance_list

In [ ]:
high_relevance(df,'삶의만족도')

['소득만족도']