# 파이썬과 SQL 연동을 위한 Anaconda, JupyterNotebook  설치
- [파이썬 로컬환경구성](https://drive.google.com/file/d/1lhTPY9c24n-L0bgDfDFPZTnBwMyjPfYu/view?usp=drive_link)

# 파이썬에서 MySQL 사용하기
1. 연결을 위한 모듈 pymysql 설치 및 불러오기
```
!pip install pymysql
import pymysql
```
2. MySQL 연결
```
connect = pymysql.connect(
    host='host',
    user ='user_name',
    password='password',
    db='database_name',
    charset='utf8/utf8mb4')
```
3. 실행결과를 돌려받는 통로인 커서 만들기
```
cursor = connect.cursor()
```
4. 커서 실행
```
cursor.execute("sql_statement")
```
5. 변경내용 저장
```
connect.commit()
```
6. MySQL 연결 해제
```
connect.close()
```

In [ ]:
# MySQL 연결
import pymysql
connect = pymysql.connect(
    host='localhost',   # MySQL 서버 주소 (예: '127.0.0.1' 또는 'server-ip')
    port=3306,          # MySQL 포트 번호 (기본값: 3306)
    user='root',        # MySQL 사용자 이름
    password='0000',    # MySQL 비밀번호
    db='test',          # 사용할 데이터베이스 이름
    charset='utf8mb4'   # 문자세트(데이터형태)
)

In [ ]:
# 커서 생성
cursor = connect.cursor()

In [ ]:
# 커서 실행 (데이터 조회)
cursor.execute("SELECT * FROM sales")

In [ ]:
# 커서 실행 (테이블 생성)
cursor.execute("""CREATE TABLE customer
                    (id INT AUTO_INCREMENT PRIMARY KEY,
                     name VARCHAR(100) NOT NULL,
                     email VARCHAR(200))""")

In [ ]:
# 커서 실행 (데이터 입력)
cursor.execute("INSERT INTO customer(name) VALUES('임선미')")
cursor.execute("INSERT INTO customer(name) VALUES('김지훈')")
cursor.execute("INSERT INTO customer(name) VALUES('멋사')")

In [ ]:
# 변경내용 저장
connect.commit()

In [ ]:
# MySQL 연결 종료
connect.close()

In [ ]:
# 데이터 입력 프로그램
cursor = connect.cursor()
while (True) :
    name = input("사용자 이름 ==> ")
    if name == "" :
        print("사용자 이름은 필수 입력 사항입니다.")
        continue
    email = input("사용자 이메일 ==> ")
    sql = "INSERT INTO customer VALUES('" + name + "','" + email + "')"
    cursor.execute(sql)

In [ ]:
# 데이터 조회 프로그램
cursor = connect.cursor()
cursor.execute("SELECT * FROM customer")

print("사용자ID    사용자이름    이메일")
print("--------------------------------")

while (True) :
    row = cursor.fetchone()     #데이터를 한 행씩 가져오기
    if row== None :
        break
    customer_id = row[0]
    name = row[1]
    email = row[2]
    print("%5s   %15s   %20s" % (customer_id, name, email)) #%5s는 자리수 지정

In [ ]:
# 조회된 데이터를 데이터프레임으로 변경
import pandas as pd
result = cursor.fetchall()                              #데이터를 전체 가져오기
columns = [column[0] for column in cursor.description]  #컬럼명 가져오기
df = pd.DataFrame(result, columns = columns)
df

# SQL을 Python과 연동하여 데이터 핸들링 연습
- world DB를 연결

In [3]:
import pymysql
conn = pymysql.connect(
    host = 'localhost',
    port = 3306,
    user = 'root',
    password ='0000',
    db = 'world',
    charset ='utf8mb4')

cur = conn.cursor()

In [13]:
# country 테이블에서
# GovernmentForm 필드의 데이터를 내림차순으로 정렬하여 조회
cur.execute("SELECT * FROM country ORDER BY GovernmentForm DESC")
one = cur.fetchall()
columns = [col[0] for col in cur.description]
df_one = pd.DataFrame(one, columns = columns)
df_one.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,GUM,Guam,Oceania,Micronesia,549.00,NaN,168000,77.8,1197.00,1136.00,Guam,US Territory,George W. Bush,921.0,GU
1,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.00,NaN,93000,78.1,0.00,None,Virgin Islands of the United States,US Territory,George W. Bush,4067.0,VI
2,ASM,American Samoa,Oceania,Polynesia,199.00,NaN,68000,75.1,334.00,None,Amerika Samoa,US Territory,George W. Bush,54.0,AS
3,HMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359.00,NaN,0,None,0.00,None,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
4,NFK,Norfolk Island,Oceania,Australia and New Zealand,36.00,NaN,2000,None,0.00,None,Norfolk Island,Territory of Australia,Elisabeth II,2806.0,NF

In [14]:
# country 테이블에서
# GovernmentForm 필드 기준으로 내림차순으로 정렬한 후
# SurfaceArea 필드 기준으로 오름차순 정렬하여 조회
cur.execute("SELECT * FROM country ORDER BY GovernmentForm DESC, SurfaceArea")
two = cur.fetchall()
columns = [col[0] for col in cur.description]
df_two = pd.DataFrame(two, columns = columns)
df_two.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ASM,American Samoa,Oceania,Polynesia,199.00,NaN,68000,75.1,334.00,None,Amerika Samoa,US Territory,George W. Bush,54.0,AS
1,VIR,"Virgin Islands, U.S.",North America,Caribbean,347.00,NaN,93000,78.1,0.00,None,Virgin Islands of the United States,US Territory,George W. Bush,4067.0,VI
2,GUM,Guam,Oceania,Micronesia,549.00,NaN,168000,77.8,1197.00,1136.00,Guam,US Territory,George W. Bush,921.0,GU
3,CCK,Cocos (Keeling) Islands,Oceania,Australia and New Zealand,14.00,NaN,600,None,0.00,None,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317.0,CC
4,NFK,Norfolk Island,Oceania,Australia and New Zealand,36.00,NaN,2000,None,0.00,None,Norfolk Island,Territory of Australia,Elisabeth II,2806.0,NF

In [15]:
# country 테이블에서
# Continent 필드가 'Africa'인 데이터 중에
# Population 기준으로 오름차순 정렬한 후
# Name, Population 데이터
cur.execute("SELECT * FROM country WHERE Continent = 'Africa' ORDER BY Population")
three = cur.fetchall()
columns = [col[0] for col in cur.description]
df_three = pd.DataFrame(three, columns = columns)
df_three.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.00,NaN,0,None,0.00,None,British Indian Ocean Territory,Dependent Territory of the UK,Elisabeth II,NaN,IO
1,SHN,Saint Helena,Africa,Western Africa,314.00,NaN,6000,76.8,0.00,None,Saint Helena,Dependent Territory of the UK,Elisabeth II,3063.0,SH
2,SYC,Seychelles,Africa,Eastern Africa,455.00,1976.0,77000,70.4,536.00,539.00,Sesel/Seychelles,Republic,France-Albert René,3206.0,SC
3,STP,Sao Tome and Principe,Africa,Central Africa,964.00,1975.0,147000,65.3,6.00,None,São Tomé e Príncipe,Republic,Miguel Trovoada,3172.0,ST
4,MYT,Mayotte,Africa,Eastern Africa,373.00,NaN,149000,59.5,0.00,None,Mayotte,Territorial Collectivity of France,Jacques Chirac,2514.0,YT

In [16]:
# country 테이블에서 Continent 필드로 그룹화하고
# GNP 평균값을 소수점 2자로 반올림하여 조회하고 이름을 avg_GNP로 출력
cur.execute("SELECT Continent, ROUND(AVG(GNP),2) AS avg_GNP FROM country GROUP BY Continent")
four = cur.fetchall()
columns = [col[0] for col in cur.description]
df_four = pd.DataFrame(four, columns = columns)
df_four.head()

       Continent    avg_GNP
0  North America  261854.79
1           Asia  150105.73
2         Africa   10006.47
3         Europe  206497.07
4  South America  107991.00

In [17]:
# country 테이블에서 Region 필드로 그룹화하고
# 나라의 개수가 15이상 20이하인 데이터를 count_reg로 하여 내림차순으로 조회
cur.execute("""SELECT Region, COUNT(Region) AS count_reg 
            FROM country 
            GROUP BY Region 
            HAVING count_reg BETWEEN 15 AND 20 
            ORDER BY count_reg DESC""")
five = cur.fetchall()
columns = [col[0] for col in cur.description]
df_five = pd.DataFrame(five, columns = columns)
df_five.head()

            Region  count_reg
0   Eastern Africa         20
1      Middle East         18
2   Western Africa         17
3  Southern Europe         15

In [18]:
# country 테이블의 각 국가마다
# 해당 국가에 소속된 도시들의 평균 인구를 city 테이블을 이용하여 조회
cur.execute("""SELECT t.Name, AVG(c.Population)
            FROM country t JOIN city c ON t.Code = c.CountryCode 
            GROUP BY t.Name""")
six = cur.fetchall()
columns = [col[0] for col in cur.description]
df_six = pd.DataFrame(six, columns = columns)
df_six.head()

          Name AVG(c.Population)
0        Aruba        29034.0000
1  Afghanistan       583025.0000
2       Angola       512320.0000
3     Anguilla          778.0000
4      Albania       270000.0000

In [19]:
# country 테이블의 Frace의 국가코드를 이용하여
# city 테이블의 'France'의 모든 도시의 이름 출력
cur.execute("""SELECT * FROM city 
               WHERE CountryCode = (
                    SELECT Code FROM country WHERE Name = 'France')""")
seven = cur.fetchall()
columns = [col[0] for col in cur.description]
df_seven = pd.DataFrame(seven, columns = columns)
df_seven.head()

     ID       Name CountryCode             District  Population
0  2974      Paris         FRA        Île-de-France     2125246
1  2975  Marseille         FRA  Provence-Alpes-Côte      798430
2  2976       Lyon         FRA          Rhône-Alpes      445452
3  2977   Toulouse         FRA        Midi-Pyrénées      390350
4  2978       Nice         FRA  Provence-Alpes-Côte      342738

In [20]:
# world DB의 city와 country 테이블과 이용하여
# 도시 인구 비율 계산 함수 (도시인구/해당 국가의 인구)
def city_pop_ratio(city_name):
    cur.execute(f"""SELECT c.Population, t.Population
                   FROM city c JOIN country t ON c.CountryCode = t.Code
                   WHERE c.Name='{city_name}'""")
    city_pop, country_pop = cur.fetchone()
    return round(city_pop/country_pop*100, 2)

In [21]:
city_pop_ratio("Seoul")

21.31