In [1]:
import pandas as pd

In [21]:
# 보건
a = pd.read_csv('/content/Life-Expectancy-Data-Updated.csv')
# 노동시장
b = pd.read_csv('/content/unemployment analysis.csv')
# 대기오염
c = pd.read_csv('/content/Measurement_summary.csv')
# 세계자살률 및 사회경제
d = pd.read_csv('/content/master.csv')
# 시카고 범죄 데이터
e = pd.read_csv('/content/Chicago_Crimes_2001_to_2004.csv', on_bad_lines='skip')
# 세계 소득 불평등
f = pd.read_csv('/content/WIID_06MAY2020.csv')
# 글로벌 테러리즘 데이터 베이스
g = pd.read_excel('/content/globalterrorismdb_0522dist.xlsx')
# 뉴욕시 311 서비스 요청 데이터

<ipython-input-21-1cbbfd17b585>:10: DtypeWarning: Columns (17,20) have mixed types. Specify dtype option on import or set low_memory=False.
  e = pd.read_csv('/content/Chicago_Crimes_2001_to_2004.csv', on_bad_lines='skip')

In [5]:
a.head()

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
0,Turkiye,Middle East,2015,11.1,13.0,105.8240,1.32,97,65,27.8,...,97,0.08,11006,78.53,4.9,4.8,7.8,0,1,76.5
1,Spain,European Union,2015,2.7,3.3,57.9025,10.35,97,94,26.0,...,97,0.09,25742,46.44,0.6,0.5,9.7,1,0,82.8
2,India,Asia,2007,51.5,67.9,201.0765,1.57,60,35,21.2,...,64,0.13,1076,1183.21,27.1,28.0,5.0,0,1,65.4
3,Guyana,South America,2006,32.8,40.5,222.1965,5.68,93,74,25.3,...,93,0.79,4146,0.75,5.7,5.5,7.9,0,1,67.0
4,Israel,Middle East,2012,3.4,4.3,57.9510,2.89,97,89,27.0,...,94,0.08,33995,7.91,1.2,1.1,12.8,1,0,81.7

In [6]:
# 연도별 데이터 개수 확인
year_counts = a["Year"].value_counts().sort_index()
print(year_counts)

Year
2000    179
2001    179
2002    179
2003    179
2004    179
2005    179
2006    179
2007    179
2008    179
2009    179
2010    179
2011    179
2012    179
2013    179
2014    179
2015    179
Name: count, dtype: int64

In [12]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2864 entries, 0 to 2863
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      2864 non-null   object
 1   Region                       2864 non-null   object
 2   Year                         2864 non-null   int64
 3   Infant_deaths                2864 non-null   float64
 4   Under_five_deaths            2864 non-null   float64
 5   Adult_mortality              2864 non-null   float64
 6   Alcohol_consumption          2864 non-null   float64
 7   Hepatitis_B                  2864 non-null   int64
 8   Measles                      2864 non-null   int64
 9   BMI                          2864 non-null   float64
 10  Polio                        2864 non-null   int64
 11  Diphtheria                   2864 non-null   int64
 12  Incidents_HIV                2864 non-null   float64
 13  GDP_per_capita               2864 non-null   int64
 14  Population_mln               2864 non-null   float64
 15  Thinness_ten_nineteen_years  2864 non-null   float64
 16  Thinness_five_nine_years     2864 non-null   float64
 17  Schooling                    2864 non-null   float64
 18  Economy_status_Developed     2864 non-null   int64
 19  Economy_status_Developing    2864 non-null   int64
 20  Life_expectancy              2864 non-null   float64
dtypes: float64(11), int64(8), object(2)
memory usage: 470.0+ KB

In [7]:
b.head()

,Country Name,Country Code,1991,1992,1993,1994,1995,1996,1997,1998,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Africa Eastern and Southern,AFE,7.80,7.84,7.85,7.84,7.83,7.84,7.86,7.81,...,6.56,6.45,6.41,6.49,6.61,6.71,6.73,6.91,7.56,8.11
1,Afghanistan,AFG,10.65,10.82,10.72,10.73,11.18,10.96,10.78,10.80,...,11.34,11.19,11.14,11.13,11.16,11.18,11.15,11.22,11.71,13.28
2,Africa Western and Central,AFW,4.42,4.53,4.55,4.54,4.53,4.57,4.60,4.66,...,4.64,4.41,4.69,4.63,5.57,6.02,6.04,6.06,6.77,6.84
3,Angola,AGO,4.21,4.21,4.23,4.16,4.11,4.10,4.09,4.07,...,7.35,7.37,7.37,7.39,7.41,7.41,7.42,7.42,8.33,8.53
4,Albania,ALB,10.31,30.01,25.26,20.84,14.61,13.93,16.88,20.05,...,13.38,15.87,18.05,17.19,15.42,13.62,12.30,11.47,13.33,11.82

In [13]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  235 non-null    object
 1   Country Code  235 non-null    object
 2   1991          235 non-null    float64
 3   1992          235 non-null    float64
 4   1993          235 non-null    float64
 5   1994          235 non-null    float64
 6   1995          235 non-null    float64
 7   1996          235 non-null    float64
 8   1997          235 non-null    float64
 9   1998          235 non-null    float64
 10  1999          235 non-null    float64
 11  2000          235 non-null    float64
 12  2001          235 non-null    float64
 13  2002          235 non-null    float64
 14  2003          235 non-null    float64
 15  2004          235 non-null    float64
 16  2005          235 non-null    float64
 17  2006          235 non-null    float64
 18  2007          235 non-null    float64
 19  2008          235 non-null    float64
 20  2009          235 non-null    float64
 21  2010          235 non-null    float64
 22  2011          235 non-null    float64
 23  2012          235 non-null    float64
 24  2013          235 non-null    float64
 25  2014          235 non-null    float64
 26  2015          235 non-null    float64
 27  2016          235 non-null    float64
 28  2017          235 non-null    float64
 29  2018          235 non-null    float64
 30  2019          235 non-null    float64
 31  2020          235 non-null    float64
 32  2021          235 non-null    float64
dtypes: float64(31), object(2)
memory usage: 60.7+ KB

In [8]:
c.head()

,Measurement date,Station code,Address,Latitude,Longitude,SO2,NO2,O3,CO,PM10,PM2.5
0,2017-01-01 00:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008,0.004,0.059,0.002,1.2,73.0,57.0
1,2017-01-01 01:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008,0.004,0.058,0.002,1.2,71.0,59.0
2,2017-01-01 02:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008,0.004,0.056,0.002,1.2,70.0,59.0
3,2017-01-01 03:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008,0.004,0.056,0.002,1.2,70.0,58.0
4,2017-01-01 04:00,101,"19, Jong-ro 35ga-gil, Jongno-gu, Seoul, Republ...",37.572016,127.005008,0.003,0.051,0.002,1.2,69.0,61.0

In [14]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 647511 entries, 0 to 647510
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Measurement date  647511 non-null  object
 1   Station code      647511 non-null  int64
 2   Address           647511 non-null  object
 3   Latitude          647511 non-null  float64
 4   Longitude         647511 non-null  float64
 5   SO2               647511 non-null  float64
 6   NO2               647511 non-null  float64
 7   O3                647511 non-null  float64
 8   CO                647511 non-null  float64
 9   PM10              647511 non-null  float64
 10  PM2.5             647511 non-null  float64
dtypes: float64(8), int64(1), object(2)
memory usage: 54.3+ MB

In [9]:
d.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [10]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             27820 non-null  object
 1   year                27820 non-null  int64
 2   sex                 27820 non-null  object
 3   age                 27820 non-null  object
 4   suicides_no         27820 non-null  int64
 5   population          27820 non-null  int64
 6   suicides/100k pop   27820 non-null  float64
 7   country-year        27820 non-null  object
 8   HDI for year        8364 non-null   float64
 9    gdp_for_year ($)   27820 non-null  object
 10  gdp_per_capita ($)  27820 non-null  int64
 11  generation          27820 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB

In [11]:
e.head()

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,879,4786321,HM399414,01/01/2004 12:01:00 AM,082XX S COLES AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,...,7.0,46.0,06,NaN,NaN,2004.0,08/17/2015 03:03:40 PM,NaN,NaN,NaN
1,2544,4676906,HM278933,03/01/2003 12:00:00 AM,004XX W 42ND PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,...,11.0,61.0,26,1173974.0,1876757.0,2003.0,04/15/2016 08:55:02 AM,41.817229,-87.637328,"(41.817229156, -87.637328162)"
2,2919,4789749,HM402220,06/20/2004 11:00:00 AM,025XX N KIMBALL AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,...,35.0,22.0,20,NaN,NaN,2004.0,08/17/2015 03:03:40 PM,NaN,NaN,NaN
3,2927,4789765,HM402058,12/30/2004 08:00:00 PM,045XX W MONTANA ST,0840,THEFT,FINANCIAL ID THEFT: OVER $300,OTHER,False,...,31.0,20.0,06,NaN,NaN,2004.0,08/17/2015 03:03:40 PM,NaN,NaN,NaN
4,3302,4677901,HM275615,05/01/2003 01:00:00 AM,111XX S NORMAL AVE,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,...,34.0,49.0,06,1174948.0,1831051.0,2003.0,04/15/2016 08:55:02 AM,41.691785,-87.635116,"(41.691784636, -87.635115968)"

In [15]:
e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1923515 entries, 0 to 1923514
Data columns (total 23 columns):
 #   Column                Dtype
---  ------                -----
 0   Unnamed: 0            int64
 1   ID                    int64
 2   Case Number           object
 3   Date                  object
 4   Block                 object
 5   IUCR                  object
 6   Primary Type          object
 7   Description           object
 8   Location Description  object
 9   Arrest                bool
 10  Domestic              bool
 11  Beat                  int64
 12  District              float64
 13  Ward                  float64
 14  Community Area        float64
 15  FBI Code              object
 16  X Coordinate          float64
 17  Y Coordinate          object
 18  Year                  float64
 19  Updated On            object
 20  Latitude              object
 21  Longitude             float64
 22  Location              object
dtypes: bool(2), float64(6), int64(3), object(12)
memory usage: 311.8+ MB

In [16]:
e.isnull().sum()

Unnamed: 0                   0
ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description        16
Arrest                       0
Domestic                     0
Beat                         0
District                     2
Ward                    700132
Community Area          700247
FBI Code                     0
X Coordinate             30691
Y Coordinate             30691
Year                         0
Updated On                   0
Latitude                 30691
Longitude                30692
Location                 30692
dtype: int64

In [17]:
f.head()

,Unnamed: 0,id,country,c3,c2,year,gini_reported,palma,ratio_top20bottom20,bottom40,...,gdp_ppp_pc_usd2011,population,revision,quality,quality_score,source,source_detailed,source_comments,survey,link
0,0,1,Afghanistan,AFG,AF,2008,29.00,NaN,4.33,22.00,...,1268.0,27722282.0,New 2019,High,12,National statistical authority,European Union and the Central Statistics Orga...,NaN,Living Conditions Survey (LCS),https://cso-of-afghanistan.shinyapps.io/ALCS_D...
1,1,2,Afghanistan,AFG,AF,2012,33.00,NaN,4.11,23.00,...,1773.0,31161378.0,New 2019,High,12,National statistical authority,European Union and the Central Statistics Orga...,NaN,Living Conditions Survey (LCS),https://cso-of-afghanistan.shinyapps.io/ALCS_D...
2,2,3,Afghanistan,AFG,AF,2017,31.00,NaN,4.44,22.00,...,1758.0,36296108.0,New 2019,High,12,National statistical authority,European Union and the Central Statistics Orga...,NaN,Living Conditions Survey (LCS),https://eeas.europa.eu/regions/asia/44072/resu...
3,3,4,Albania,ALB,AL,1996,27.01,0.93,3.95,22.85,...,4635.0,3098699.0,New 2019,Average,13,World Bank,World Bank 2019,PovcalNet,NaN,http://iresearch.worldbank.org/PovcalNet/povOn...
4,4,5,Albania,ALB,AL,2002,31.74,1.22,4.83,20.93,...,6088.0,3126183.0,New 2019,Average,13,World Bank,World Bank 2019,PovcalNet,NaN,http://iresearch.worldbank.org/PovcalNet/povOn...

In [18]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11826 entries, 0 to 11825
Data columns (total 60 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           11826 non-null  int64
 1   id                   11826 non-null  int64
 2   country              11826 non-null  object
 3   c3                   11826 non-null  object
 4   c2                   11816 non-null  object
 5   year                 11826 non-null  int64
 6   gini_reported        11747 non-null  float64
 7   palma                6714 non-null   float64
 8   ratio_top20bottom20  7503 non-null   float64
 9   bottom40             7459 non-null   float64
 10  q1                   7576 non-null   float64
 11  q2                   7354 non-null   float64
 12  q3                   7375 non-null   float64
 13  q4                   7381 non-null   float64
 14  q5                   7577 non-null   float64
 15  d1                   6671 non-null   float64
 16  d2                   6587 non-null   float64
 17  d3                   6587 non-null   float64
 18  d4                   6587 non-null   float64
 19  d5                   6607 non-null   float64
 20  d6                   6612 non-null   float64
 21  d7                   6618 non-null   float64
 22  d8                   6615 non-null   float64
 23  d9                   6634 non-null   float64
 24  d10                  6777 non-null   float64
 25  bottom5              1928 non-null   float64
 26  top5                 2568 non-null   float64
 27  resource             11825 non-null  object
 28  resource_detailed    11826 non-null  object
 29  scale                11325 non-null  object
 30  scale_detailed       11325 non-null  object
 31  sharing_unit         11331 non-null  object
 32  reference_unit       11789 non-null  object
 33  areacovr             11826 non-null  object
 34  areacovr_detailed    11826 non-null  object
 35  popcovr              11826 non-null  object
 36  popcovr_detailed     11826 non-null  object
 37  region_un            11826 non-null  object
 38  region_un_sub        11826 non-null  object
 39  region_wb            11826 non-null  object
 40  eu                   11826 non-null  object
 41  oecd                 11826 non-null  object
 42  incomegroup          11826 non-null  object
 43  mean                 6417 non-null   float64
 44  median               5003 non-null   float64
 45  currency             7356 non-null   object
 46  reference_period     7417 non-null   object
 47  exchangerate         6301 non-null   float64
 48  mean_usd             135 non-null    float64
 49  median_usd           59 non-null     float64
 50  gdp_ppp_pc_usd2011   8300 non-null   float64
 51  population           11765 non-null  float64
 52  revision             7827 non-null   object
 53  quality              11825 non-null  object
 54  quality_score        11826 non-null  int64
 55  source               11826 non-null  object
 56  source_detailed      11826 non-null  object
 57  source_comments      5941 non-null   object
 58  survey               5578 non-null   object
 59  link                 3340 non-null   object
dtypes: float64(28), int64(4), object(28)
memory usage: 5.4+ MB

In [19]:
f["year"].value_counts().sort_index()

year
1867      1
1890      1
1900      1
1910      1
1914      1
       ...
2014    345
2015    286
2016    241
2017    139
2018     55
Name: count, Length: 91, dtype: int64

In [22]:
g.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaT,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaT,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaT,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaT,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaT,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [23]:
g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209706 entries, 0 to 209705
Columns: 135 entries, eventid to related
dtypes: datetime64[ns](1), float64(54), int64(23), object(57)
memory usage: 216.0+ MB

In [29]:
# 각 컬럼별 NaN 값의 개수를 확인
null_counts = g.isnull().sum()

# NaN이 아닌 값의 개수를 확인
non_null_counts = g.shape[0] - null_counts
pd.set_option('display.max_rows', 500)

# 결과 출력
print(non_null_counts)

eventid               209706
iyear                 209706
imonth                209706
iday                  209706
approxdate             12689
extended              209706
resolution              4861
country               209706
country_txt           209706
region                209706
region_txt            209706
provstate             209706
city                  209279
latitude              205015
longitude             205014
specificity           209705
vicinity              209706
location               67475
summary               143586
crit1                 209706
crit2                 209706
crit3                 209706
doubtterr             209706
alternative            35249
alternative_txt        35249
multiple              209705
success               209706
suicide               209706
attacktype1           209706
attacktype1_txt       209706
attacktype2             8434
attacktype2_txt         8434
attacktype3              658
attacktype3_txt          658
targtype1             209706
targtype1_txt         209706
targsubtype1          197867
targsubtype1_txt      197867
corp1                 167170
target1               209069
natlty1               207692
natlty1_txt           207692
targtype2              14535
targtype2_txt          14535
targsubtype2           14003
targsubtype2_txt       14003
corp2                  13508
target2                14410
natlty2                14211
natlty2_txt            14211
targtype3               1629
targtype3_txt           1629
targsubtype3            1539
targsubtype3_txt        1539
corp3                   1478
target3                 1628
natlty3                 1600
natlty3_txt             1600
gname                 209706
gsubname                7230
gname2                  2579
gsubname2                184
gname3                   414
gsubname3                 23
motive                 55058
guncertain1           209326
guncertain2             2538
guncertain3              410
individual            209706
nperps                138613
nperpcap              140233
claimed               143613
claimmode              24696
claimmode_txt          24696
claim2                  2476
claimmode2               732
claimmode2_txt           732
claim3                   409
claimmode3               140
claimmode3_txt           140
compclaim               4954
weaptype1             209706
weaptype1_txt         209706
weapsubtype1          183765
weapsubtype1_txt      183765
weaptype2              16402
weaptype2_txt          16402
weapsubtype2           14292
weapsubtype2_txt       14292
weaptype3               2371
weaptype3_txt           2371
weapsubtype3            2132
weapsubtype3_txt        2132
weaptype4                 73
weaptype4_txt             73
weapsubtype4              70
weapsubtype4_txt          70
weapdetail            123137
nkill                 197179
nkillus               145269
nkillter              141547
nwound                189770
nwoundus              145009
nwoundte              138800
property              209706
propextent             73464
propextent_txt         73464
propvalue              48375
propcomment            67424
ishostkid             209528
nhostkid               16667
nhostkidus             16612
nhours                  4985
ndays                  10301
divert                   338
kidhijcountry           3313
ransom                 80466
ransomamt               1533
ransomamtus              734
ransompaid               951
ransompaidus             725
ransomnote               573
hostkidoutcome         14091
hostkidoutcome_txt     14091
nreleased              13494
addnotes               35809
scite1                143524
scite2                 92743
scite3                 52676
dbsource              209706
INT_LOG               209706
INT_IDEO              209706
INT_MISC              209706
INT_ANY               209706
related                30604
dtype: int64

In [25]:
import geopandas as gpd

gdf = gpd.read_file("/content/nyc_zip_code_tabulation_areas_polygons.geojson")

In [26]:
gdf.head()

,cartodb_id,objectid,postalcode,po_name,state,borough,st_fips,cty_fips,bldgpostalcode,shape_leng,shape_area,id,geometry
0,173,173,11693,Far Rockaway,NY,Brooklyn,36,047,0,9479.917277,3.497516e+06,http://nyc.pediacities.com/Resource/PostalCode...,"MULTIPOLYGON (((-73.84076 40.62536, -73.84306 ..."
1,48,48,10463,Bronx,NY,Manhattan,36,061,0,7791.517127,3.119702e+06,http://nyc.pediacities.com/Resource/PostalCode...,"MULTIPOLYGON (((-73.91544 40.87559, -73.91509 ..."
2,51,51,10033,New York,NY,Manhattan,36,061,0,29415.607123,1.615605e+07,http://nyc.pediacities.com/Resource/PostalCode...,"MULTIPOLYGON (((-73.93213 40.86945, -73.93128 ..."
3,120,120,11367,Flushing,NY,Queens,36,081,0,33506.126605,7.281015e+07,http://nyc.pediacities.com/Resource/PostalCode...,"MULTIPOLYGON (((-73.83761 40.74324, -73.83516 ..."
4,64,64,10472,Bronx,NY,Bronx,36,005,0,27006.042411,3.096325e+07,http://nyc.pediacities.com/Resource/PostalCode...,"MULTIPOLYGON (((-73.88011 40.83723, -73.87747 ..."

In [27]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cartodb_id      262 non-null    int32
 1   objectid        262 non-null    int32
 2   postalcode      262 non-null    object
 3   po_name         262 non-null    object
 4   state           262 non-null    object
 5   borough         262 non-null    object
 6   st_fips         262 non-null    object
 7   cty_fips        262 non-null    object
 8   bldgpostalcode  262 non-null    int32
 9   shape_leng      262 non-null    float64
 10  shape_area      262 non-null    float64
 11  id              262 non-null    object
 12  geometry        262 non-null    geometry
dtypes: float64(2), geometry(1), int32(3), object(7)
memory usage: 23.7+ KB

In [ ]:
# 우리나라 범죄 데이터 테러데이터랑 비교 생각중