In [1]:
import pandas as pd

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
chicago = pd.read_csv('/content/drive/MyDrive/final_csv/chicago_crime_data_preprocessing.csv',on_bad_lines='skip' )
chicago.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,4676906,HM278933,03/01/2003 12:00:00 AM,004XX W 42ND PL,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,True,...,11.0,61.0,26,1173974.0,1876757.0,2003.0,04/15/2016 08:55:02 AM,41.817229,-87.637328,"(41.817229156, -87.637328162)"
1,4677901,HM275615,05/01/2003 01:00:00 AM,111XX S NORMAL AVE,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,...,34.0,49.0,06,1174948.0,1831051.0,2003.0,04/15/2016 08:55:02 AM,41.691785,-87.635116,"(41.691784636, -87.635115968)"
2,4791194,HM403711,01/01/2001 11:00:00 AM,114XX S ST LAWRENCE AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,True,True,...,9.0,50.0,02,1182247.0,1829375.0,2001.0,08/29/2006 03:46:28 AM,41.687020,-87.608445,"(41.687020002, -87.60844523)"
3,4679521,HM216293,03/15/2003 12:00:00 AM,090XX S RACINE AVE,5007,OTHER OFFENSE,OTHER WEAPONS VIOLATION,RESIDENCE PORCH/HALLWAY,False,False,...,21.0,73.0,26,1169911.0,1844832.0,2003.0,04/15/2016 08:55:02 AM,41.729712,-87.653159,"(41.729712374, -87.653158513)"
4,4680124,HM282389,01/01/2003 12:00:00 AM,009XX S SPAULDING AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,24.0,29.0,06,1154521.0,1895755.0,2003.0,04/15/2016 08:55:02 AM,41.869772,-87.708180,"(41.869772159, -87.708180162)"

## Date 컬럼


    - Date 컬럼
      date/time 형식으로 되어있음
    - date와 time 컬럼 추가해서 따로 분석할 수 있게 나누기

In [4]:
chicago.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                    float64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [5]:
# Date 컬럼의 형식 object(문자열) -> 형식 변환
chicago['Date'] = pd.to_datetime(chicago['Date'], format='%m/%d/%Y %I:%M:%S %p')

In [6]:
# 날짜(Date)와 시간(Time) 나누기
chicago['F_Date'] = chicago['Date'].dt.strftime('%Y-%m-%d')
chicago['Time'] = chicago['Date'].dt.strftime('%H:%M:%S')

# 결과 출력
print(chicago[['F_Date', 'Time']])

             F_Date      Time
0        2003-03-01  00:00:00
1        2003-05-01  01:00:00
2        2001-01-01  11:00:00
3        2003-03-15  00:00:00
4        2003-01-01  00:00:00
...             ...       ...
7836595  2016-05-03  23:33:00
7836596  2016-05-03  23:30:00
7836597  2016-05-03  00:15:00
7836598  2016-05-03  21:07:00
7836599  2016-05-03  23:38:00

[7836600 rows x 2 columns]

In [7]:
chicago.to_csv('/content/drive/MyDrive/final_csv/chicago_final.csv', index=False)