In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 데이터 전처리
one = pd.read_csv('/content/drive/MyDrive/chicago_crime_data_with_ward_community1.csv', on_bad_lines='skip')
two = pd.read_csv('/content/drive/MyDrive/chicago_crime_data_with_ward_community2.csv', on_bad_lines='skip')
three = pd.read_csv('/content/drive/MyDrive/chicago_crime_data_with_ward_community3.csv', on_bad_lines='skip')
four = pd.read_csv('/content/drive/MyDrive/chicago_crime_data_with_ward_community4.csv', on_bad_lines='skip')

# 데이터 합치기
df = pd.concat([one, two, three, four], axis=0, ignore_index=True)

df = df.drop(columns='Unnamed: 0') # 의미 없는 열 삭제

# 결측치 삭제
df = df.dropna(subset=['Location'])

In [ ]:
df.isna().sum()

ID                         0
Case Number                6
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1486
Arrest                     0
Domestic                   0
Beat                       0
District                  91
Ward                     601
Community Area           482
FBI Code                   0
X Coordinate               0
Y Coordinate               0
Year                       0
Updated On                 0
Latitude                   0
Longitude                  0
Location                   0
dtype: int64

In [ ]:
# 'District', 'Ward', 'Community Area' 열에서 결측치가 있는 행 삭제
df = df.dropna(subset=['District', 'Ward', 'Community Area'])

In [ ]:
df.isna().sum()

ID                         0
Case Number                6
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description    1486
Arrest                     0
Domestic                   0
Beat                       0
District                   0
Ward                       0
Community Area             0
FBI Code                   0
X Coordinate               0
Y Coordinate               0
Year                       0
Updated On                 0
Latitude                   0
Longitude                  0
Location                   0
dtype: int64

In [ ]:
# 결과를 CSV로 저장
df.to_csv('/content/drive/MyDrive/chicago_crime_data_preprocessing.csv', index=False)