In [1]:
import pandas as pd
insta = pd.read_csv('/content/top_insta_influencers_data.csv')
insta.head()

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country
0,1,cristiano,92,3.3k,475.8m,8.7m,1.39%,6.5m,29.0b,Spain
1,2,kyliejenner,91,6.9k,366.2m,8.3m,1.62%,5.9m,57.4b,United States
2,3,leomessi,90,0.89k,357.3m,6.8m,1.24%,4.4m,6.0b,NaN
3,4,selenagomez,93,1.8k,342.7m,6.2m,0.97%,3.3m,11.5b,United States
4,5,therock,91,6.8k,334.1m,1.9m,0.20%,665.3k,12.5b,United States

### 팔로워 TOP 10

In [2]:
#팔로워 Top 10
insta.sort_values(by='followers',ascending=False).head(10)

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country
33,34,dualipa,74,1.3k,85.9m,2.1m,1.26%,1.1m,2.6b,United Kingdom
34,35,gal_gadot,85,1.7k,85.6m,1.4m,0.69%,586.5k,2.3b,United States
35,36,vindiesel,88,1.8k,82.3m,1.4m,0.60%,482.3k,2.5b,United States
36,37,nasa,88,3.6k,81.3m,1.2m,1.53%,1.2m,4.2b,United States
37,38,priyankachopra,85,3.6k,81.1m,1.6m,1.00%,802.9k,5.6b,United States
38,39,lalalalisa_m,70,0.87k,80.9m,5.8m,9.00%,7.2m,5.1b,NaN
39,40,Shakira,88,2.0k,76.1m,975.1k,0.41%,304.7k,1.9b,NaN
41,42,gigihadid,85,3.3k,75.3m,2.5m,2.56%,1.9m,8.2b,United States
40,41,snoopdogg,86,10.0k,75.3m,203.7k,0.17%,125.8k,2.0b,NaN
42,43,davidbeckham,86,1.5k,74.9m,1.2m,0.46%,340.9k,1.9b,United States

### 포스트당 평균 참여율 컬럼 생성

In [3]:
# 문자열을 숫자형으로 변환 (변환 불가능한 값은 NaN으로 처리)
insta['avg_likes'] = pd.to_numeric(insta['avg_likes'], errors='coerce')
insta['followers'] = pd.to_numeric(insta['followers'], errors='coerce')

# 참여율 계산
insta['engagement_rate'] = insta['avg_likes'] / insta['followers']

In [4]:
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rank               200 non-null    int64
 1   channel_info       200 non-null    object
 2   influence_score    200 non-null    int64
 3   posts              200 non-null    object
 4   followers          0 non-null      float64
 5   avg_likes          0 non-null      float64
 6   60_day_eng_rate    200 non-null    object
 7   new_post_avg_like  200 non-null    object
 8   total_likes        200 non-null    object
 9   country            138 non-null    object
 10  engagement_rate    0 non-null      float64
dtypes: float64(3), int64(2), object(6)
memory usage: 17.3+ KB

In [5]:
insta.head()

,rank,channel_info,influence_score,posts,followers,avg_likes,60_day_eng_rate,new_post_avg_like,total_likes,country,engagement_rate
0,1,cristiano,92,3.3k,NaN,NaN,1.39%,6.5m,29.0b,Spain,NaN
1,2,kyliejenner,91,6.9k,NaN,NaN,1.62%,5.9m,57.4b,United States,NaN
2,3,leomessi,90,0.89k,NaN,NaN,1.24%,4.4m,6.0b,NaN,NaN
3,4,selenagomez,93,1.8k,NaN,NaN,0.97%,3.3m,11.5b,United States,NaN
4,5,therock,91,6.8k,NaN,NaN,0.20%,665.3k,12.5b,United States,NaN